version: '3'

services:
    nginx:
        image: nginx:stable-alpine
        container_name: "${PROJECT_NAME}_nginx"
        restart: always
        ports:
            - "${HTTP_PORT}:80"
        volumes:
            - $PWD/proyecto:/var/www/html
            - $PWD/nginx/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
        networks:
            - LEMP
        restart: always


    php:
        build: ./php
        container_name: "${PROJECT_NAME}_php"
        restart: always
        volumes:
            - $PWD/proyecto:/var/www/html
        expose:
            - "9000"       
        networks:
            - LEMP
        depends_on: 
            - laravel-composer
        restart: always


    laravel-composer: 
        build: ./composer
        container_name: "${PROJECT_NAME}_composer"
        restart: always
        command: bash -c "sh /script.sh"
        volumes:
            - ./proyecto:/home/mariossan
        networks:
            - LEMP


    db:
        image: mysql:8
        container_name: "${PROJECT_NAME}_db"
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
            MYSQL_DATABASE: "${DB_NAME}"
        ports:
            - "${DB_PORT_EXT}:3306"
        networks:
            - LEMP
        volumes:
            - $PWD/mysql:/var/lib/mysql
        restart: always
networks:
    LEMP:
